org: saatwik
app: remind-me
service: remind-me

frameworkVersion: '3'

provider:
  name: aws
  stage: dev
  runtime: python3.8
  timeout: 10
  memorySize: 128
  region: ap-south-1
  versionFunctions: false
  profile: seconduser
  stackName: saatwik-remindme-app



functions:
  hello:
    handler: handler.hello
    description: This function will handle the functions that perform CRUD operations
    events:
      - httpApi:
          path: /viewtasks
          method: GET
      - httpApi:
          path: /createtasks
          method: POST
      - httpApi:
          path: /deletetasks
          method: DELETE
      - httpApi:
          path: /updatetasks
          method: PUT