org: saatwik
app: remind-me
service: remind-me

frameworkVersion: '3'

provider:
  name: aws
  stage: dev
  runtime: python3.8
  timeout: 900
  memorySize: 128
  region: ap-south-1
  versionFunctions: false
  profile: second_user
  stackName: saatwik-remindme-app
  add  environment:
    DYNAMODB_CUSTOMER_TABLE: remind_me_table
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'dynamodb:PutItem'
            - 'dynamodb:Get*'
            - 'dynamodb:Scan*'
            - 'dynamodb:UpdateItem'
            - 'dynamodb:DeleteItem'
          Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/remind_me_table

custom:
  pythonRequirements:
    dockerizePip: true

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**

functions:
  hello:
    handler: handler.hello
    description: This function will handle the functions that perform CRUD operations
    events:
      - httpApi:
          path: /viewtasks
          method: GET
      - httpApi:
          path: /createtasks
          method: POST
      - httpApi:
          path: /deletetasks
          method: DELETE
      - httpApi:
          path: /updatetasks
          method: PUT
plugins:
  - serverless-python-requirements
