name: CI

on:
  push:
    branches:
      - remind-me_v0.01

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 17.6.x
    strategy:
      matrix:
        python-version:
        - 3.8
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ env.NODE-VERSION }}
        uses: actions/setup-node@v1
        with:
           node-version: ${{ env.NODE-VERSION }}
      - name: Install Dependencies
        run: npm install
      - name: Serverless Deploy
        uses: dhollerbach/github-action-serverless-with-python-requirements@master
        env:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
