name: CI

on:
  push:
    branches: ["remind-me_v0.01"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project
